config/routes.rb
Rails.application.routes.draw do
  resources :candidates do
    member do
      post :vote
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/candidate.rb
class Candidate < ApplicationRecord

  validates :name, presence: true
  has_many :vote_logs
end

app/models/vote_log.rb
class VoteLog < ApplicationRecord
  belongs_to :candidate, counter_cache: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController

  before_action :find_candidate, only: [:show, :edit, :update, :destroy, :vote]
                                #  except: [:new, :create, :index]

  def index
    @candidates = Candidate.all
  end

  def show
  end

  def new
    @candidate = Candidate.new
  end

  def create
    @candidate = Candidate.new(candidate_params)

    if @candidate.save
      redirect_to '/candidates', notice: 'Candidate created'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
      if @candidate.update(candidate_params)
        redirect_to '/candidates',notice: 'Candidate updated!'
      else
      render :edit, status: :unprocessable_entity
      end
  end

  def destroy
      @candidate.destroy
        redirect_to '/candidates',notice: 'Candidate deleted!'
  end

  def vote
    # VoteLog.create(candidate: @candidate, ip_address: request.remote_ip)
    @candidate.vote_logs.create(ip_address: request.remote_ip)
    redirect_to '/candidates',notice: 'voted!'
  end

  private
  def candidate_params
      params.require(:candidate).permit(:name, :party, :age, :politics)
  end

  def find_candidate
     @candidate = Candidate.find_by(id: params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/candidates_helper.rb
module CandidatesHelper
end

app/views/candidates/_form.html.erb
<% if candidate.errors.any? %>
  <ul>
    <% candidate.errors.full_messages.each do |message| %>
      <li>
        <%= message %>
      </li>
      <% end %>
  </ul>

  <% end %>

    <%= form_for(candidate) do |form| %>
      <div>
        <%= form.label :name %>
          <%= form.text_field :name %>
      </div>

      <div>
        <%= form.label :party %>
          <%= form.text_field :party %>
      </div>

      <div>
        <%= form.label :age %>
          <%= form.text_field :age %>
      </div>

      <div>
        <%= form.label :politics %>
          <%= form.text_area :politics %>
      </div>

      <%= form.submit %>
        <% end %>

app/views/candidates/edit.html.erb
<h1>Edit candidate</h1>

<%= render 'form' , candidate: @candidate %>

app/views/candidates/index.html.erb
<h1>index</h1>

  <%= link_to 'Add Candidate' , new_candidate_path %>

    <table>
      <tr>
        <td>Votes</td>
        <td>Name</td>
        <td>party</td>
        <td>Age</td>
        <td>Action</td>

        <% @candidates.each do |candidate| %>
      <tr>
        <td>
          <%= candidate.vote_logs.size %>
        </td>
        <td>
          <form action="candidates/<%= candidate.id %>/vote" method="post">
            <button type="submit">vote</button>
          </form>
          <!-- <%= link_to 'vote' , vote_candidate_path(candidate.id), method: :post %> -->
        </td>
        <td>
          <%= link_to candidate.name, candidate_path(candidate.id) %>
        </td>
        <td>
          <%= candidate.party %>
        </td>
        <td>
          <%= candidate.age %>
        </td>
        <td>
          <%= link_to 'update' , edit_candidate_path(candidate.id) %>
            <%= link_to 'delete' , candidate_path(candidate.id), data: { turbo_method:
              :delete,turbo_confirm: "Are you sure?" } %>
        </td>
      </tr>

      <% end %>

        </tr>
    </table>

app/views/candidates/new.html.erb
<h1>Add candidate</h1>

<%= render 'form' , candidate: @candidate %>

app/views/candidates/show.html.erb
<% if @candidate %>
  <h1>
    <%= @candidate.name %>
  </h1>

  <ul>
    <li>
      party: <%= @candidate.party %>
    </li>
    <li>
      age: <%= @candidate.age %>
    </li>
    <li>
      politics: <%= @candidate.politics %>
    </li>
  </ul>


  <% else %>
    <h1>No Record Found!</h1>

    <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VoteMe2Rails7</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= notice %>
    <%= yield %>
  </body>
</html>